//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::category::Entity as Category;
pub use super::person::Entity as Person;
pub use super::service::Entity as Service;
pub use super::service_categories::Entity as ServiceCategories;
pub use super::user_categories::Entity as UserCategories;
